apiVersion: v1
kind: Deployment
metadata:
  name: nginx-demo

spec:
  replicas: 3
  selector:
    matchLabels:
      aaa: bbb
  template:
    metadata:
      labels:
        app: nginx-demo
  
    spec:
      containers:
        - name: nginx-demo
          image: nginx:latest  
          ports:
            - containerPort: 80

